//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.20 at 09:54:46 PM CEST 
//


package org.niso.pdfs.datadict;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for compressiontypeNiso.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="compressiontypeNiso">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Uncompressed"/>
 *     &lt;enumeration value="CCITT 1D"/>
 *     &lt;enumeration value="CCITT Group 3"/>
 *     &lt;enumeration value="CCITT Group 4"/>
 *     &lt;enumeration value="LZW"/>
 *     &lt;enumeration value="JPG"/>
 *     &lt;enumeration value="PNG"/>
 *     &lt;enumeration value="DJVU"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "compressiontypeNiso")
@XmlEnum
public enum CompressiontypeNiso {

    @XmlEnumValue("Uncompressed")
    UNCOMPRESSED("Uncompressed"),
    @XmlEnumValue("CCITT 1D")
    CCITT_1_D("CCITT 1D"),
    @XmlEnumValue("CCITT Group 3")
    CCITT_GROUP_3("CCITT Group 3"),
    @XmlEnumValue("CCITT Group 4")
    CCITT_GROUP_4("CCITT Group 4"),
    LZW("LZW"),
    JPG("JPG"),
    PNG("PNG"),
    DJVU("DJVU");
    private final String value;

    CompressiontypeNiso(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CompressiontypeNiso fromValue(String v) {
        for (CompressiontypeNiso c: CompressiontypeNiso.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
