//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.20 at 09:54:46 PM CEST 
//


package org.niso.pdfs.datadict;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 		Nonostante lo schema NISO sia nato per descrivere le caratteristiche tecniche di file contenenti immagini, per ragioni di omogenità si è scelto di usare il medesimo formato anche per file text-oriented 
 * 		
 * 
 * <p>Java class for docFormat complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="docFormat">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mime" type="{http://www.niso.org/pdfs/DataDict.pdf}doc_mimetypeNiso"/>
 *         &lt;element name="compression" type="{http://www.niso.org/pdfs/DataDict.pdf}doc_compressiontypeNiso" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "docFormat", propOrder = {
    "name",
    "mime",
    "compression"
})
public class DocFormat {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected DocMimetypeNiso mime;
    protected DocCompressiontypeNiso compression;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the mime property.
     * 
     * @return
     *     possible object is
     *     {@link DocMimetypeNiso }
     *     
     */
    public DocMimetypeNiso getMime() {
        return mime;
    }

    /**
     * Sets the value of the mime property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocMimetypeNiso }
     *     
     */
    public void setMime(DocMimetypeNiso value) {
        this.mime = value;
    }

    /**
     * Gets the value of the compression property.
     * 
     * @return
     *     possible object is
     *     {@link DocCompressiontypeNiso }
     *     
     */
    public DocCompressiontypeNiso getCompression() {
        return compression;
    }

    /**
     * Sets the value of the compression property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocCompressiontypeNiso }
     *     
     */
    public void setCompression(DocCompressiontypeNiso value) {
        this.compression = value;
    }

}
