//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.20 at 09:54:46 PM CEST 
//


package org.niso.pdfs.datadict;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.niso.pdfs.datadict package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.niso.pdfs.datadict
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ImageCreation }
     * 
     */
    public ImageCreation createImageCreation() {
        return new ImageCreation();
    }

    /**
     * Create an instance of {@link DocFormat }
     * 
     */
    public DocFormat createDocFormat() {
        return new DocFormat();
    }

    /**
     * Create an instance of {@link Spatialmetrics }
     * 
     */
    public Spatialmetrics createSpatialmetrics() {
        return new Spatialmetrics();
    }

    /**
     * Create an instance of {@link Format }
     * 
     */
    public Format createFormat() {
        return new Format();
    }

    /**
     * Create an instance of {@link Targetdata }
     * 
     */
    public Targetdata createTargetdata() {
        return new Targetdata();
    }

    /**
     * Create an instance of {@link Dimensions }
     * 
     */
    public Dimensions createDimensions() {
        return new Dimensions();
    }

    /**
     * Create an instance of {@link ImageCreation.Scanningsystem }
     * 
     */
    public ImageCreation.Scanningsystem createImageCreationScanningsystem() {
        return new ImageCreation.Scanningsystem();
    }

}
