//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.21 at 04:07:06 PM CEST 
//


package gov.loc.mix.v20;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for captureDeviceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="captureDeviceType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="transmission scanner"/>
 *     &lt;enumeration value="reflection print scanner"/>
 *     &lt;enumeration value="digital still camera"/>
 *     &lt;enumeration value="still from video"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "captureDeviceType")
@XmlEnum
public enum CaptureDeviceType {

    @XmlEnumValue("transmission scanner")
    TRANSMISSION_SCANNER("transmission scanner"),
    @XmlEnumValue("reflection print scanner")
    REFLECTION_PRINT_SCANNER("reflection print scanner"),
    @XmlEnumValue("digital still camera")
    DIGITAL_STILL_CAMERA("digital still camera"),
    @XmlEnumValue("still from video")
    STILL_FROM_VIDEO("still from video");
    private final String value;

    CaptureDeviceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CaptureDeviceType fromValue(String v) {
        for (CaptureDeviceType c: CaptureDeviceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
