//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.02 at 08:11:10 PM GMT+01:00 
//


package gov.loc.mods.v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for modsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="modsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{http://www.loc.gov/mods/v3}titleInfo"/>
 *         &lt;element ref="{http://www.loc.gov/mods/v3}name"/>
 *         &lt;element ref="{http://www.loc.gov/mods/v3}typeOfResource"/>
 *         &lt;element ref="{http://www.loc.gov/mods/v3}genre"/>
 *         &lt;element ref="{http://www.loc.gov/mods/v3}originInfo"/>
 *         &lt;element ref="{http://www.loc.gov/mods/v3}language"/>
 *         &lt;element ref="{http://www.loc.gov/mods/v3}physicalDescription"/>
 *         &lt;element ref="{http://www.loc.gov/mods/v3}abstract"/>
 *         &lt;element ref="{http://www.loc.gov/mods/v3}tableOfContents"/>
 *         &lt;element ref="{http://www.loc.gov/mods/v3}targetAudience"/>
 *         &lt;element ref="{http://www.loc.gov/mods/v3}note"/>
 *         &lt;element ref="{http://www.loc.gov/mods/v3}subject"/>
 *         &lt;element ref="{http://www.loc.gov/mods/v3}classification"/>
 *         &lt;element ref="{http://www.loc.gov/mods/v3}relatedItem"/>
 *         &lt;element ref="{http://www.loc.gov/mods/v3}identifier"/>
 *         &lt;element ref="{http://www.loc.gov/mods/v3}location"/>
 *         &lt;element ref="{http://www.loc.gov/mods/v3}accessCondition"/>
 *         &lt;element name="extension" type="{http://www.loc.gov/mods/v3}extensionType"/>
 *         &lt;element ref="{http://www.loc.gov/mods/v3}recordInfo"/>
 *       &lt;/choice>
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="version">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="3.0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "modsType", propOrder = {
    "titleInfoOrNameOrTypeOfResource"
})
@XmlSeeAlso({
    RelatedItemType.class,
    Mods.class
})
public class ModsType {

    @XmlElementRefs({
        @XmlElementRef(name = "identifier", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
        @XmlElementRef(name = "name", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
        @XmlElementRef(name = "originInfo", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
        @XmlElementRef(name = "genre", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
        @XmlElementRef(name = "recordInfo", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
        @XmlElementRef(name = "location", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
        @XmlElementRef(name = "titleInfo", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
        @XmlElementRef(name = "subject", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
        @XmlElementRef(name = "language", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
        @XmlElementRef(name = "extension", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
        @XmlElementRef(name = "relatedItem", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
        @XmlElementRef(name = "typeOfResource", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
        @XmlElementRef(name = "accessCondition", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
        @XmlElementRef(name = "abstract", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
        @XmlElementRef(name = "tableOfContents", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
        @XmlElementRef(name = "classification", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
        @XmlElementRef(name = "physicalDescription", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
        @XmlElementRef(name = "targetAudience", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class),
        @XmlElementRef(name = "note", namespace = "http://www.loc.gov/mods/v3", type = JAXBElement.class)
    })
    protected List<JAXBElement<?>> titleInfoOrNameOrTypeOfResource;
    @XmlAttribute(name = "ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute
    protected String version;

    /**
     * Gets the value of the titleInfoOrNameOrTypeOfResource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the titleInfoOrNameOrTypeOfResource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitleInfoOrNameOrTypeOfResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link IdentifierType }{@code >}
     * {@link JAXBElement }{@code <}{@link NameType }{@code >}
     * {@link JAXBElement }{@code <}{@link OriginInfoType }{@code >}
     * {@link JAXBElement }{@code <}{@link RecordInfoType }{@code >}
     * {@link JAXBElement }{@code <}{@link GenreType }{@code >}
     * {@link JAXBElement }{@code <}{@link LocationType }{@code >}
     * {@link JAXBElement }{@code <}{@link TitleInfoType }{@code >}
     * {@link JAXBElement }{@code <}{@link SubjectType }{@code >}
     * {@link JAXBElement }{@code <}{@link LanguageType }{@code >}
     * {@link JAXBElement }{@code <}{@link RelatedItemType }{@code >}
     * {@link JAXBElement }{@code <}{@link ExtensionType }{@code >}
     * {@link JAXBElement }{@code <}{@link TypeOfResourceType }{@code >}
     * {@link JAXBElement }{@code <}{@link UnstructuredText }{@code >}
     * {@link JAXBElement }{@code <}{@link UnstructuredText }{@code >}
     * {@link JAXBElement }{@code <}{@link UnstructuredText }{@code >}
     * {@link JAXBElement }{@code <}{@link ClassificationType }{@code >}
     * {@link JAXBElement }{@code <}{@link PhysicalDescriptionType }{@code >}
     * {@link JAXBElement }{@code <}{@link TargetAudienceType }{@code >}
     * {@link JAXBElement }{@code <}{@link UnstructuredText }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getTitleInfoOrNameOrTypeOfResource() {
        if (titleInfoOrNameOrTypeOfResource == null) {
            titleInfoOrNameOrTypeOfResource = new ArrayList<JAXBElement<?>>();
        }
        return this.titleInfoOrNameOrTypeOfResource;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
