//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.02 at 08:11:10 PM GMT+01:00 
//


package gov.loc.mods.v3;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.loc.mods.v3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RelatedItem_QNAME = new QName("http://www.loc.gov/mods/v3", "relatedItem");
    private final static QName _PhysicalDescription_QNAME = new QName("http://www.loc.gov/mods/v3", "physicalDescription");
    private final static QName _Abstract_QNAME = new QName("http://www.loc.gov/mods/v3", "abstract");
    private final static QName _TargetAudience_QNAME = new QName("http://www.loc.gov/mods/v3", "targetAudience");
    private final static QName _Language_QNAME = new QName("http://www.loc.gov/mods/v3", "language");
    private final static QName _Identifier_QNAME = new QName("http://www.loc.gov/mods/v3", "identifier");
    private final static QName _AccessCondition_QNAME = new QName("http://www.loc.gov/mods/v3", "accessCondition");
    private final static QName _Classification_QNAME = new QName("http://www.loc.gov/mods/v3", "classification");
    private final static QName _TitleInfo_QNAME = new QName("http://www.loc.gov/mods/v3", "titleInfo");
    private final static QName _TypeOfResource_QNAME = new QName("http://www.loc.gov/mods/v3", "typeOfResource");
    private final static QName _Genre_QNAME = new QName("http://www.loc.gov/mods/v3", "genre");
    private final static QName _Location_QNAME = new QName("http://www.loc.gov/mods/v3", "location");
    private final static QName _Subject_QNAME = new QName("http://www.loc.gov/mods/v3", "subject");
    private final static QName _TableOfContents_QNAME = new QName("http://www.loc.gov/mods/v3", "tableOfContents");
    private final static QName _OriginInfo_QNAME = new QName("http://www.loc.gov/mods/v3", "originInfo");
    private final static QName _Note_QNAME = new QName("http://www.loc.gov/mods/v3", "note");
    private final static QName _Name_QNAME = new QName("http://www.loc.gov/mods/v3", "name");
    private final static QName _RecordInfo_QNAME = new QName("http://www.loc.gov/mods/v3", "recordInfo");
    private final static QName _DetailTypeNumber_QNAME = new QName("http://www.loc.gov/mods/v3", "number");
    private final static QName _DetailTypeCaption_QNAME = new QName("http://www.loc.gov/mods/v3", "caption");
    private final static QName _DetailTypeTitle_QNAME = new QName("http://www.loc.gov/mods/v3", "title");
    private final static QName _OriginInfoTypeCopyrightDate_QNAME = new QName("http://www.loc.gov/mods/v3", "copyrightDate");
    private final static QName _OriginInfoTypeDateCreated_QNAME = new QName("http://www.loc.gov/mods/v3", "dateCreated");
    private final static QName _OriginInfoTypeDateIssued_QNAME = new QName("http://www.loc.gov/mods/v3", "dateIssued");
    private final static QName _OriginInfoTypeIssuance_QNAME = new QName("http://www.loc.gov/mods/v3", "issuance");
    private final static QName _OriginInfoTypeDateCaptured_QNAME = new QName("http://www.loc.gov/mods/v3", "dateCaptured");
    private final static QName _OriginInfoTypeFrequency_QNAME = new QName("http://www.loc.gov/mods/v3", "frequency");
    private final static QName _OriginInfoTypePlace_QNAME = new QName("http://www.loc.gov/mods/v3", "place");
    private final static QName _OriginInfoTypeDateValid_QNAME = new QName("http://www.loc.gov/mods/v3", "dateValid");
    private final static QName _OriginInfoTypePublisher_QNAME = new QName("http://www.loc.gov/mods/v3", "publisher");
    private final static QName _OriginInfoTypeEdition_QNAME = new QName("http://www.loc.gov/mods/v3", "edition");
    private final static QName _OriginInfoTypeDateModified_QNAME = new QName("http://www.loc.gov/mods/v3", "dateModified");
    private final static QName _OriginInfoTypeDateOther_QNAME = new QName("http://www.loc.gov/mods/v3", "dateOther");
    private final static QName _SubjectTypeCartographics_QNAME = new QName("http://www.loc.gov/mods/v3", "cartographics");
    private final static QName _SubjectTypeTopic_QNAME = new QName("http://www.loc.gov/mods/v3", "topic");
    private final static QName _SubjectTypeHierarchicalGeographic_QNAME = new QName("http://www.loc.gov/mods/v3", "hierarchicalGeographic");
    private final static QName _SubjectTypeGeographic_QNAME = new QName("http://www.loc.gov/mods/v3", "geographic");
    private final static QName _SubjectTypeOccupation_QNAME = new QName("http://www.loc.gov/mods/v3", "occupation");
    private final static QName _SubjectTypeTemporal_QNAME = new QName("http://www.loc.gov/mods/v3", "temporal");
    private final static QName _SubjectTypeGeographicCode_QNAME = new QName("http://www.loc.gov/mods/v3", "geographicCode");
    private final static QName _SubjectTypeHierarchicalGeographicContinent_QNAME = new QName("http://www.loc.gov/mods/v3", "continent");
    private final static QName _SubjectTypeHierarchicalGeographicProvince_QNAME = new QName("http://www.loc.gov/mods/v3", "province");
    private final static QName _SubjectTypeHierarchicalGeographicState_QNAME = new QName("http://www.loc.gov/mods/v3", "state");
    private final static QName _SubjectTypeHierarchicalGeographicCountry_QNAME = new QName("http://www.loc.gov/mods/v3", "country");
    private final static QName _SubjectTypeHierarchicalGeographicCity_QNAME = new QName("http://www.loc.gov/mods/v3", "city");
    private final static QName _SubjectTypeHierarchicalGeographicIsland_QNAME = new QName("http://www.loc.gov/mods/v3", "island");
    private final static QName _SubjectTypeHierarchicalGeographicRegion_QNAME = new QName("http://www.loc.gov/mods/v3", "region");
    private final static QName _SubjectTypeHierarchicalGeographicTerritory_QNAME = new QName("http://www.loc.gov/mods/v3", "territory");
    private final static QName _SubjectTypeHierarchicalGeographicArea_QNAME = new QName("http://www.loc.gov/mods/v3", "area");
    private final static QName _SubjectTypeHierarchicalGeographicCounty_QNAME = new QName("http://www.loc.gov/mods/v3", "county");
    private final static QName _ModsTypeExtension_QNAME = new QName("http://www.loc.gov/mods/v3", "extension");
    private final static QName _RecordInfoTypeRecordCreationDate_QNAME = new QName("http://www.loc.gov/mods/v3", "recordCreationDate");
    private final static QName _RecordInfoTypeRecordContentSource_QNAME = new QName("http://www.loc.gov/mods/v3", "recordContentSource");
    private final static QName _RecordInfoTypeRecordIdentifier_QNAME = new QName("http://www.loc.gov/mods/v3", "recordIdentifier");
    private final static QName _RecordInfoTypeLanguageOfCataloging_QNAME = new QName("http://www.loc.gov/mods/v3", "languageOfCataloging");
    private final static QName _RecordInfoTypeRecordOrigin_QNAME = new QName("http://www.loc.gov/mods/v3", "recordOrigin");
    private final static QName _RecordInfoTypeRecordChangeDate_QNAME = new QName("http://www.loc.gov/mods/v3", "recordChangeDate");
    private final static QName _NameTypeRole_QNAME = new QName("http://www.loc.gov/mods/v3", "role");
    private final static QName _NameTypeNamePart_QNAME = new QName("http://www.loc.gov/mods/v3", "namePart");
    private final static QName _NameTypeAffiliation_QNAME = new QName("http://www.loc.gov/mods/v3", "affiliation");
    private final static QName _NameTypeDisplayForm_QNAME = new QName("http://www.loc.gov/mods/v3", "displayForm");
    private final static QName _NameTypeDescription_QNAME = new QName("http://www.loc.gov/mods/v3", "description");
    private final static QName _PhysicalDescriptionTypeDigitalOrigin_QNAME = new QName("http://www.loc.gov/mods/v3", "digitalOrigin");
    private final static QName _PhysicalDescriptionTypeReformattingQuality_QNAME = new QName("http://www.loc.gov/mods/v3", "reformattingQuality");
    private final static QName _PhysicalDescriptionTypeForm_QNAME = new QName("http://www.loc.gov/mods/v3", "form");
    private final static QName _PhysicalDescriptionTypeExtent_QNAME = new QName("http://www.loc.gov/mods/v3", "extent");
    private final static QName _PhysicalDescriptionTypeInternetMediaType_QNAME = new QName("http://www.loc.gov/mods/v3", "internetMediaType");
    private final static QName _TitleInfoTypeNonSort_QNAME = new QName("http://www.loc.gov/mods/v3", "nonSort");
    private final static QName _TitleInfoTypePartNumber_QNAME = new QName("http://www.loc.gov/mods/v3", "partNumber");
    private final static QName _TitleInfoTypeSubTitle_QNAME = new QName("http://www.loc.gov/mods/v3", "subTitle");
    private final static QName _TitleInfoTypePartName_QNAME = new QName("http://www.loc.gov/mods/v3", "partName");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.loc.mods.v3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ModsType }
     * 
     */
    public ModsType createModsType() {
        return new ModsType();
    }

    /**
     * Create an instance of {@link ClassificationType }
     * 
     */
    public ClassificationType createClassificationType() {
        return new ClassificationType();
    }

    /**
     * Create an instance of {@link PlaceType }
     * 
     */
    public PlaceType createPlaceType() {
        return new PlaceType();
    }

    /**
     * Create an instance of {@link LanguageType.LanguageTerm }
     * 
     */
    public LanguageType.LanguageTerm createLanguageTypeLanguageTerm() {
        return new LanguageType.LanguageTerm();
    }

    /**
     * Create an instance of {@link ModsCollection }
     * 
     */
    public ModsCollection createModsCollection() {
        return new ModsCollection();
    }

    /**
     * Create an instance of {@link PartType }
     * 
     */
    public PartType createPartType() {
        return new PartType();
    }

    /**
     * Create an instance of {@link LanguageType }
     * 
     */
    public LanguageType createLanguageType() {
        return new LanguageType();
    }

    /**
     * Create an instance of {@link PhysicalDescriptionType }
     * 
     */
    public PhysicalDescriptionType createPhysicalDescriptionType() {
        return new PhysicalDescriptionType();
    }

    /**
     * Create an instance of {@link SourceType }
     * 
     */
    public SourceType createSourceType() {
        return new SourceType();
    }

    /**
     * Create an instance of {@link RoleType }
     * 
     */
    public RoleType createRoleType() {
        return new RoleType();
    }

    /**
     * Create an instance of {@link LocationType.PhysicalLocation }
     * 
     */
    public LocationType.PhysicalLocation createLocationTypePhysicalLocation() {
        return new LocationType.PhysicalLocation();
    }

    /**
     * Create an instance of {@link RelatedItemType }
     * 
     */
    public RelatedItemType createRelatedItemType() {
        return new RelatedItemType();
    }

    /**
     * Create an instance of {@link SubjectType.Cartographics }
     * 
     */
    public SubjectType.Cartographics createSubjectTypeCartographics() {
        return new SubjectType.Cartographics();
    }

    /**
     * Create an instance of {@link SubjectType.GeographicCode }
     * 
     */
    public SubjectType.GeographicCode createSubjectTypeGeographicCode() {
        return new SubjectType.GeographicCode();
    }

    /**
     * Create an instance of {@link TypeOfResourceType }
     * 
     */
    public TypeOfResourceType createTypeOfResourceType() {
        return new TypeOfResourceType();
    }

    /**
     * Create an instance of {@link ExtensionType }
     * 
     */
    public ExtensionType createExtensionType() {
        return new ExtensionType();
    }

    /**
     * Create an instance of {@link DateType }
     * 
     */
    public DateType createDateType() {
        return new DateType();
    }

    /**
     * Create an instance of {@link SubjectType }
     * 
     */
    public SubjectType createSubjectType() {
        return new SubjectType();
    }

    /**
     * Create an instance of {@link GenreType }
     * 
     */
    public GenreType createGenreType() {
        return new GenreType();
    }

    /**
     * Create an instance of {@link RoleType.RoleTerm }
     * 
     */
    public RoleType.RoleTerm createRoleTypeRoleTerm() {
        return new RoleType.RoleTerm();
    }

    /**
     * Create an instance of {@link NamePartType }
     * 
     */
    public NamePartType createNamePartType() {
        return new NamePartType();
    }

    /**
     * Create an instance of {@link PhysicalDescriptionType.Form }
     * 
     */
    public PhysicalDescriptionType.Form createPhysicalDescriptionTypeForm() {
        return new PhysicalDescriptionType.Form();
    }

    /**
     * Create an instance of {@link RecordInfoType.RecordIdentifier }
     * 
     */
    public RecordInfoType.RecordIdentifier createRecordInfoTypeRecordIdentifier() {
        return new RecordInfoType.RecordIdentifier();
    }

    /**
     * Create an instance of {@link BaseDateType }
     * 
     */
    public BaseDateType createBaseDateType() {
        return new BaseDateType();
    }

    /**
     * Create an instance of {@link RecordInfoType }
     * 
     */
    public RecordInfoType createRecordInfoType() {
        return new RecordInfoType();
    }

    /**
     * Create an instance of {@link PlaceTermType }
     * 
     */
    public PlaceTermType createPlaceTermType() {
        return new PlaceTermType();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link UnstructuredText }
     * 
     */
    public UnstructuredText createUnstructuredText() {
        return new UnstructuredText();
    }

    /**
     * Create an instance of {@link ExtentType }
     * 
     */
    public ExtentType createExtentType() {
        return new ExtentType();
    }

    /**
     * Create an instance of {@link TargetAudienceType }
     * 
     */
    public TargetAudienceType createTargetAudienceType() {
        return new TargetAudienceType();
    }

    /**
     * Create an instance of {@link IdentifierType }
     * 
     */
    public IdentifierType createIdentifierType() {
        return new IdentifierType();
    }

    /**
     * Create an instance of {@link LocationType.Url }
     * 
     */
    public LocationType.Url createLocationTypeUrl() {
        return new LocationType.Url();
    }

    /**
     * Create an instance of {@link SubjectType.HierarchicalGeographic }
     * 
     */
    public SubjectType.HierarchicalGeographic createSubjectTypeHierarchicalGeographic() {
        return new SubjectType.HierarchicalGeographic();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link TitleInfoType }
     * 
     */
    public TitleInfoType createTitleInfoType() {
        return new TitleInfoType();
    }

    /**
     * Create an instance of {@link DetailType }
     * 
     */
    public DetailType createDetailType() {
        return new DetailType();
    }

    /**
     * Create an instance of {@link OriginInfoType }
     * 
     */
    public OriginInfoType createOriginInfoType() {
        return new OriginInfoType();
    }

    /**
     * Create an instance of {@link Mods }
     * 
     */
    public Mods createMods() {
        return new Mods();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelatedItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "relatedItem")
    public JAXBElement<RelatedItemType> createRelatedItem(RelatedItemType value) {
        return new JAXBElement<RelatedItemType>(_RelatedItem_QNAME, RelatedItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PhysicalDescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "physicalDescription")
    public JAXBElement<PhysicalDescriptionType> createPhysicalDescription(PhysicalDescriptionType value) {
        return new JAXBElement<PhysicalDescriptionType>(_PhysicalDescription_QNAME, PhysicalDescriptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnstructuredText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "abstract")
    public JAXBElement<UnstructuredText> createAbstract(UnstructuredText value) {
        return new JAXBElement<UnstructuredText>(_Abstract_QNAME, UnstructuredText.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TargetAudienceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "targetAudience")
    public JAXBElement<TargetAudienceType> createTargetAudience(TargetAudienceType value) {
        return new JAXBElement<TargetAudienceType>(_TargetAudience_QNAME, TargetAudienceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LanguageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "language")
    public JAXBElement<LanguageType> createLanguage(LanguageType value) {
        return new JAXBElement<LanguageType>(_Language_QNAME, LanguageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "identifier")
    public JAXBElement<IdentifierType> createIdentifier(IdentifierType value) {
        return new JAXBElement<IdentifierType>(_Identifier_QNAME, IdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnstructuredText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "accessCondition")
    public JAXBElement<UnstructuredText> createAccessCondition(UnstructuredText value) {
        return new JAXBElement<UnstructuredText>(_AccessCondition_QNAME, UnstructuredText.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClassificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "classification")
    public JAXBElement<ClassificationType> createClassification(ClassificationType value) {
        return new JAXBElement<ClassificationType>(_Classification_QNAME, ClassificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TitleInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "titleInfo")
    public JAXBElement<TitleInfoType> createTitleInfo(TitleInfoType value) {
        return new JAXBElement<TitleInfoType>(_TitleInfo_QNAME, TitleInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeOfResourceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "typeOfResource")
    public JAXBElement<TypeOfResourceType> createTypeOfResource(TypeOfResourceType value) {
        return new JAXBElement<TypeOfResourceType>(_TypeOfResource_QNAME, TypeOfResourceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenreType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "genre")
    public JAXBElement<GenreType> createGenre(GenreType value) {
        return new JAXBElement<GenreType>(_Genre_QNAME, GenreType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "location")
    public JAXBElement<LocationType> createLocation(LocationType value) {
        return new JAXBElement<LocationType>(_Location_QNAME, LocationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "subject")
    public JAXBElement<SubjectType> createSubject(SubjectType value) {
        return new JAXBElement<SubjectType>(_Subject_QNAME, SubjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnstructuredText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "tableOfContents")
    public JAXBElement<UnstructuredText> createTableOfContents(UnstructuredText value) {
        return new JAXBElement<UnstructuredText>(_TableOfContents_QNAME, UnstructuredText.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OriginInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "originInfo")
    public JAXBElement<OriginInfoType> createOriginInfo(OriginInfoType value) {
        return new JAXBElement<OriginInfoType>(_OriginInfo_QNAME, OriginInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnstructuredText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "note")
    public JAXBElement<UnstructuredText> createNote(UnstructuredText value) {
        return new JAXBElement<UnstructuredText>(_Note_QNAME, UnstructuredText.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "name")
    public JAXBElement<NameType> createName(NameType value) {
        return new JAXBElement<NameType>(_Name_QNAME, NameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RecordInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "recordInfo")
    public JAXBElement<RecordInfoType> createRecordInfo(RecordInfoType value) {
        return new JAXBElement<RecordInfoType>(_RecordInfo_QNAME, RecordInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "number", scope = DetailType.class)
    public JAXBElement<Object> createDetailTypeNumber(Object value) {
        return new JAXBElement<Object>(_DetailTypeNumber_QNAME, Object.class, DetailType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "caption", scope = DetailType.class)
    public JAXBElement<Object> createDetailTypeCaption(Object value) {
        return new JAXBElement<Object>(_DetailTypeCaption_QNAME, Object.class, DetailType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "title", scope = DetailType.class)
    public JAXBElement<Object> createDetailTypeTitle(Object value) {
        return new JAXBElement<Object>(_DetailTypeTitle_QNAME, Object.class, DetailType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "copyrightDate", scope = OriginInfoType.class)
    public JAXBElement<DateType> createOriginInfoTypeCopyrightDate(DateType value) {
        return new JAXBElement<DateType>(_OriginInfoTypeCopyrightDate_QNAME, DateType.class, OriginInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "dateCreated", scope = OriginInfoType.class)
    public JAXBElement<DateType> createOriginInfoTypeDateCreated(DateType value) {
        return new JAXBElement<DateType>(_OriginInfoTypeDateCreated_QNAME, DateType.class, OriginInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "dateIssued", scope = OriginInfoType.class)
    public JAXBElement<DateType> createOriginInfoTypeDateIssued(DateType value) {
        return new JAXBElement<DateType>(_OriginInfoTypeDateIssued_QNAME, DateType.class, OriginInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "issuance", scope = OriginInfoType.class)
    public JAXBElement<String> createOriginInfoTypeIssuance(String value) {
        return new JAXBElement<String>(_OriginInfoTypeIssuance_QNAME, String.class, OriginInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "dateCaptured", scope = OriginInfoType.class)
    public JAXBElement<DateType> createOriginInfoTypeDateCaptured(DateType value) {
        return new JAXBElement<DateType>(_OriginInfoTypeDateCaptured_QNAME, DateType.class, OriginInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "frequency", scope = OriginInfoType.class)
    public JAXBElement<Object> createOriginInfoTypeFrequency(Object value) {
        return new JAXBElement<Object>(_OriginInfoTypeFrequency_QNAME, Object.class, OriginInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlaceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "place", scope = OriginInfoType.class)
    public JAXBElement<PlaceType> createOriginInfoTypePlace(PlaceType value) {
        return new JAXBElement<PlaceType>(_OriginInfoTypePlace_QNAME, PlaceType.class, OriginInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "dateValid", scope = OriginInfoType.class)
    public JAXBElement<DateType> createOriginInfoTypeDateValid(DateType value) {
        return new JAXBElement<DateType>(_OriginInfoTypeDateValid_QNAME, DateType.class, OriginInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "publisher", scope = OriginInfoType.class)
    public JAXBElement<Object> createOriginInfoTypePublisher(Object value) {
        return new JAXBElement<Object>(_OriginInfoTypePublisher_QNAME, Object.class, OriginInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "edition", scope = OriginInfoType.class)
    public JAXBElement<Object> createOriginInfoTypeEdition(Object value) {
        return new JAXBElement<Object>(_OriginInfoTypeEdition_QNAME, Object.class, OriginInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "dateModified", scope = OriginInfoType.class)
    public JAXBElement<DateType> createOriginInfoTypeDateModified(DateType value) {
        return new JAXBElement<DateType>(_OriginInfoTypeDateModified_QNAME, DateType.class, OriginInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "dateOther", scope = OriginInfoType.class)
    public JAXBElement<DateType> createOriginInfoTypeDateOther(DateType value) {
        return new JAXBElement<DateType>(_OriginInfoTypeDateOther_QNAME, DateType.class, OriginInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubjectType.Cartographics }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "cartographics", scope = SubjectType.class)
    public JAXBElement<SubjectType.Cartographics> createSubjectTypeCartographics(SubjectType.Cartographics value) {
        return new JAXBElement<SubjectType.Cartographics>(_SubjectTypeCartographics_QNAME, SubjectType.Cartographics.class, SubjectType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TitleInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "titleInfo", scope = SubjectType.class)
    public JAXBElement<TitleInfoType> createSubjectTypeTitleInfo(TitleInfoType value) {
        return new JAXBElement<TitleInfoType>(_TitleInfo_QNAME, TitleInfoType.class, SubjectType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "topic", scope = SubjectType.class)
    public JAXBElement<Object> createSubjectTypeTopic(Object value) {
        return new JAXBElement<Object>(_SubjectTypeTopic_QNAME, Object.class, SubjectType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubjectType.HierarchicalGeographic }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "hierarchicalGeographic", scope = SubjectType.class)
    public JAXBElement<SubjectType.HierarchicalGeographic> createSubjectTypeHierarchicalGeographic(SubjectType.HierarchicalGeographic value) {
        return new JAXBElement<SubjectType.HierarchicalGeographic>(_SubjectTypeHierarchicalGeographic_QNAME, SubjectType.HierarchicalGeographic.class, SubjectType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "geographic", scope = SubjectType.class)
    public JAXBElement<Object> createSubjectTypeGeographic(Object value) {
        return new JAXBElement<Object>(_SubjectTypeGeographic_QNAME, Object.class, SubjectType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "occupation", scope = SubjectType.class)
    public JAXBElement<Object> createSubjectTypeOccupation(Object value) {
        return new JAXBElement<Object>(_SubjectTypeOccupation_QNAME, Object.class, SubjectType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "name", scope = SubjectType.class)
    public JAXBElement<NameType> createSubjectTypeName(NameType value) {
        return new JAXBElement<NameType>(_Name_QNAME, NameType.class, SubjectType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "temporal", scope = SubjectType.class)
    public JAXBElement<DateType> createSubjectTypeTemporal(DateType value) {
        return new JAXBElement<DateType>(_SubjectTypeTemporal_QNAME, DateType.class, SubjectType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubjectType.GeographicCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "geographicCode", scope = SubjectType.class)
    public JAXBElement<SubjectType.GeographicCode> createSubjectTypeGeographicCode(SubjectType.GeographicCode value) {
        return new JAXBElement<SubjectType.GeographicCode>(_SubjectTypeGeographicCode_QNAME, SubjectType.GeographicCode.class, SubjectType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "continent", scope = SubjectType.HierarchicalGeographic.class)
    public JAXBElement<Object> createSubjectTypeHierarchicalGeographicContinent(Object value) {
        return new JAXBElement<Object>(_SubjectTypeHierarchicalGeographicContinent_QNAME, Object.class, SubjectType.HierarchicalGeographic.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "province", scope = SubjectType.HierarchicalGeographic.class)
    public JAXBElement<Object> createSubjectTypeHierarchicalGeographicProvince(Object value) {
        return new JAXBElement<Object>(_SubjectTypeHierarchicalGeographicProvince_QNAME, Object.class, SubjectType.HierarchicalGeographic.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "state", scope = SubjectType.HierarchicalGeographic.class)
    public JAXBElement<Object> createSubjectTypeHierarchicalGeographicState(Object value) {
        return new JAXBElement<Object>(_SubjectTypeHierarchicalGeographicState_QNAME, Object.class, SubjectType.HierarchicalGeographic.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "country", scope = SubjectType.HierarchicalGeographic.class)
    public JAXBElement<Object> createSubjectTypeHierarchicalGeographicCountry(Object value) {
        return new JAXBElement<Object>(_SubjectTypeHierarchicalGeographicCountry_QNAME, Object.class, SubjectType.HierarchicalGeographic.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "city", scope = SubjectType.HierarchicalGeographic.class)
    public JAXBElement<Object> createSubjectTypeHierarchicalGeographicCity(Object value) {
        return new JAXBElement<Object>(_SubjectTypeHierarchicalGeographicCity_QNAME, Object.class, SubjectType.HierarchicalGeographic.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "island", scope = SubjectType.HierarchicalGeographic.class)
    public JAXBElement<Object> createSubjectTypeHierarchicalGeographicIsland(Object value) {
        return new JAXBElement<Object>(_SubjectTypeHierarchicalGeographicIsland_QNAME, Object.class, SubjectType.HierarchicalGeographic.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "region", scope = SubjectType.HierarchicalGeographic.class)
    public JAXBElement<Object> createSubjectTypeHierarchicalGeographicRegion(Object value) {
        return new JAXBElement<Object>(_SubjectTypeHierarchicalGeographicRegion_QNAME, Object.class, SubjectType.HierarchicalGeographic.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "territory", scope = SubjectType.HierarchicalGeographic.class)
    public JAXBElement<Object> createSubjectTypeHierarchicalGeographicTerritory(Object value) {
        return new JAXBElement<Object>(_SubjectTypeHierarchicalGeographicTerritory_QNAME, Object.class, SubjectType.HierarchicalGeographic.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "area", scope = SubjectType.HierarchicalGeographic.class)
    public JAXBElement<Object> createSubjectTypeHierarchicalGeographicArea(Object value) {
        return new JAXBElement<Object>(_SubjectTypeHierarchicalGeographicArea_QNAME, Object.class, SubjectType.HierarchicalGeographic.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "county", scope = SubjectType.HierarchicalGeographic.class)
    public JAXBElement<Object> createSubjectTypeHierarchicalGeographicCounty(Object value) {
        return new JAXBElement<Object>(_SubjectTypeHierarchicalGeographicCounty_QNAME, Object.class, SubjectType.HierarchicalGeographic.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtensionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "extension", scope = ModsType.class)
    public JAXBElement<ExtensionType> createModsTypeExtension(ExtensionType value) {
        return new JAXBElement<ExtensionType>(_ModsTypeExtension_QNAME, ExtensionType.class, ModsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "recordCreationDate", scope = RecordInfoType.class)
    public JAXBElement<DateType> createRecordInfoTypeRecordCreationDate(DateType value) {
        return new JAXBElement<DateType>(_RecordInfoTypeRecordCreationDate_QNAME, DateType.class, RecordInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SourceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "recordContentSource", scope = RecordInfoType.class)
    public JAXBElement<SourceType> createRecordInfoTypeRecordContentSource(SourceType value) {
        return new JAXBElement<SourceType>(_RecordInfoTypeRecordContentSource_QNAME, SourceType.class, RecordInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RecordInfoType.RecordIdentifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "recordIdentifier", scope = RecordInfoType.class)
    public JAXBElement<RecordInfoType.RecordIdentifier> createRecordInfoTypeRecordIdentifier(RecordInfoType.RecordIdentifier value) {
        return new JAXBElement<RecordInfoType.RecordIdentifier>(_RecordInfoTypeRecordIdentifier_QNAME, RecordInfoType.RecordIdentifier.class, RecordInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LanguageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "languageOfCataloging", scope = RecordInfoType.class)
    public JAXBElement<LanguageType> createRecordInfoTypeLanguageOfCataloging(LanguageType value) {
        return new JAXBElement<LanguageType>(_RecordInfoTypeLanguageOfCataloging_QNAME, LanguageType.class, RecordInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "recordOrigin", scope = RecordInfoType.class)
    public JAXBElement<Object> createRecordInfoTypeRecordOrigin(Object value) {
        return new JAXBElement<Object>(_RecordInfoTypeRecordOrigin_QNAME, Object.class, RecordInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "recordChangeDate", scope = RecordInfoType.class)
    public JAXBElement<DateType> createRecordInfoTypeRecordChangeDate(DateType value) {
        return new JAXBElement<DateType>(_RecordInfoTypeRecordChangeDate_QNAME, DateType.class, RecordInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RoleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "role", scope = NameType.class)
    public JAXBElement<RoleType> createNameTypeRole(RoleType value) {
        return new JAXBElement<RoleType>(_NameTypeRole_QNAME, RoleType.class, NameType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamePartType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "namePart", scope = NameType.class)
    public JAXBElement<NamePartType> createNameTypeNamePart(NamePartType value) {
        return new JAXBElement<NamePartType>(_NameTypeNamePart_QNAME, NamePartType.class, NameType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "affiliation", scope = NameType.class)
    public JAXBElement<Object> createNameTypeAffiliation(Object value) {
        return new JAXBElement<Object>(_NameTypeAffiliation_QNAME, Object.class, NameType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "displayForm", scope = NameType.class)
    public JAXBElement<Object> createNameTypeDisplayForm(Object value) {
        return new JAXBElement<Object>(_NameTypeDisplayForm_QNAME, Object.class, NameType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "description", scope = NameType.class)
    public JAXBElement<Object> createNameTypeDescription(Object value) {
        return new JAXBElement<Object>(_NameTypeDescription_QNAME, Object.class, NameType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "digitalOrigin", scope = PhysicalDescriptionType.class)
    public JAXBElement<String> createPhysicalDescriptionTypeDigitalOrigin(String value) {
        return new JAXBElement<String>(_PhysicalDescriptionTypeDigitalOrigin_QNAME, String.class, PhysicalDescriptionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnstructuredText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "note", scope = PhysicalDescriptionType.class)
    public JAXBElement<UnstructuredText> createPhysicalDescriptionTypeNote(UnstructuredText value) {
        return new JAXBElement<UnstructuredText>(_Note_QNAME, UnstructuredText.class, PhysicalDescriptionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "reformattingQuality", scope = PhysicalDescriptionType.class)
    public JAXBElement<String> createPhysicalDescriptionTypeReformattingQuality(String value) {
        return new JAXBElement<String>(_PhysicalDescriptionTypeReformattingQuality_QNAME, String.class, PhysicalDescriptionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PhysicalDescriptionType.Form }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "form", scope = PhysicalDescriptionType.class)
    public JAXBElement<PhysicalDescriptionType.Form> createPhysicalDescriptionTypeForm(PhysicalDescriptionType.Form value) {
        return new JAXBElement<PhysicalDescriptionType.Form>(_PhysicalDescriptionTypeForm_QNAME, PhysicalDescriptionType.Form.class, PhysicalDescriptionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "extent", scope = PhysicalDescriptionType.class)
    public JAXBElement<Object> createPhysicalDescriptionTypeExtent(Object value) {
        return new JAXBElement<Object>(_PhysicalDescriptionTypeExtent_QNAME, Object.class, PhysicalDescriptionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "internetMediaType", scope = PhysicalDescriptionType.class)
    public JAXBElement<Object> createPhysicalDescriptionTypeInternetMediaType(Object value) {
        return new JAXBElement<Object>(_PhysicalDescriptionTypeInternetMediaType_QNAME, Object.class, PhysicalDescriptionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "nonSort", scope = TitleInfoType.class)
    public JAXBElement<Object> createTitleInfoTypeNonSort(Object value) {
        return new JAXBElement<Object>(_TitleInfoTypeNonSort_QNAME, Object.class, TitleInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "partNumber", scope = TitleInfoType.class)
    public JAXBElement<Object> createTitleInfoTypePartNumber(Object value) {
        return new JAXBElement<Object>(_TitleInfoTypePartNumber_QNAME, Object.class, TitleInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "subTitle", scope = TitleInfoType.class)
    public JAXBElement<Object> createTitleInfoTypeSubTitle(Object value) {
        return new JAXBElement<Object>(_TitleInfoTypeSubTitle_QNAME, Object.class, TitleInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "title", scope = TitleInfoType.class)
    public JAXBElement<Object> createTitleInfoTypeTitle(Object value) {
        return new JAXBElement<Object>(_DetailTypeTitle_QNAME, Object.class, TitleInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.loc.gov/mods/v3", name = "partName", scope = TitleInfoType.class)
    public JAXBElement<Object> createTitleInfoTypePartName(Object value) {
        return new JAXBElement<Object>(_TitleInfoTypePartName_QNAME, Object.class, TitleInfoType.class, value);
    }

}
