//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.20 at 09:54:46 PM CEST 
//


package it.sbn.iccu.metaag1;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for audioproxy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="audioproxy">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="usage" type="{http://www.iccu.sbn.it/metaAG1.pdf}usages" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="file" type="{http://www.iccu.sbn.it/metaAG1.pdf}link"/>
 *         &lt;element name="md5" type="{http://www.niso.org/pdfs/DataDict.pdf}checksum"/>
 *         &lt;element name="filesize" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="audio_dimensions" type="{http://www.iccu.sbn.it/metaAG1.pdf}audio_dimensions"/>
 *         &lt;element name="audio_metrics" type="{http://www.iccu.sbn.it/metaAG1.pdf}audio_spatialmetrics" minOccurs="0"/>
 *         &lt;element name="format" type="{http://www.iccu.sbn.it/metaAG1.pdf}audio_format" minOccurs="0"/>
 *         &lt;element name="transcription" type="{http://www.iccu.sbn.it/metaAG1.pdf}audio_creation" minOccurs="0"/>
 *         &lt;element name="datetimecreated" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="audiogroupID" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "audioproxy", propOrder = {
    "usage",
    "file",
    "md5",
    "filesize",
    "audioDimensions",
    "audioMetrics",
    "format",
    "transcription",
    "datetimecreated"
})
public class Audioproxy {

    protected List<String> usage;
    @XmlElement(required = true)
    protected Link file;
    @XmlElement(required = true)
    protected String md5;
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger filesize;
    @XmlElement(name = "audio_dimensions", required = true)
    protected AudioDimensions audioDimensions;
    @XmlElement(name = "audio_metrics")
    protected AudioSpatialmetrics audioMetrics;
    protected AudioFormat format;
    protected AudioCreation transcription;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datetimecreated;
    @XmlAttribute(name = "audiogroupID")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object audiogroupID;

    /**
     * Gets the value of the usage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the usage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUsage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getUsage() {
        if (usage == null) {
            usage = new ArrayList<String>();
        }
        return this.usage;
    }

    /**
     * Gets the value of the file property.
     * 
     * @return
     *     possible object is
     *     {@link Link }
     *     
     */
    public Link getFile() {
        return file;
    }

    /**
     * Sets the value of the file property.
     * 
     * @param value
     *     allowed object is
     *     {@link Link }
     *     
     */
    public void setFile(Link value) {
        this.file = value;
    }

    /**
     * Gets the value of the md5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMd5() {
        return md5;
    }

    /**
     * Sets the value of the md5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMd5(String value) {
        this.md5 = value;
    }

    /**
     * Gets the value of the filesize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFilesize() {
        return filesize;
    }

    /**
     * Sets the value of the filesize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFilesize(BigInteger value) {
        this.filesize = value;
    }

    /**
     * Gets the value of the audioDimensions property.
     * 
     * @return
     *     possible object is
     *     {@link AudioDimensions }
     *     
     */
    public AudioDimensions getAudioDimensions() {
        return audioDimensions;
    }

    /**
     * Sets the value of the audioDimensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioDimensions }
     *     
     */
    public void setAudioDimensions(AudioDimensions value) {
        this.audioDimensions = value;
    }

    /**
     * Gets the value of the audioMetrics property.
     * 
     * @return
     *     possible object is
     *     {@link AudioSpatialmetrics }
     *     
     */
    public AudioSpatialmetrics getAudioMetrics() {
        return audioMetrics;
    }

    /**
     * Sets the value of the audioMetrics property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioSpatialmetrics }
     *     
     */
    public void setAudioMetrics(AudioSpatialmetrics value) {
        this.audioMetrics = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link AudioFormat }
     *     
     */
    public AudioFormat getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioFormat }
     *     
     */
    public void setFormat(AudioFormat value) {
        this.format = value;
    }

    /**
     * Gets the value of the transcription property.
     * 
     * @return
     *     possible object is
     *     {@link AudioCreation }
     *     
     */
    public AudioCreation getTranscription() {
        return transcription;
    }

    /**
     * Sets the value of the transcription property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioCreation }
     *     
     */
    public void setTranscription(AudioCreation value) {
        this.transcription = value;
    }

    /**
     * Gets the value of the datetimecreated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatetimecreated() {
        return datetimecreated;
    }

    /**
     * Sets the value of the datetimecreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatetimecreated(XMLGregorianCalendar value) {
        this.datetimecreated = value;
    }

    /**
     * Gets the value of the audiogroupID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getAudiogroupID() {
        return audiogroupID;
    }

    /**
     * Sets the value of the audiogroupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setAudiogroupID(Object value) {
        this.audiogroupID = value;
    }

}
