//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.20 at 09:54:46 PM CEST 
//


package it.sbn.iccu.metaag1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for audio_mimetype.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="audio_mimetype">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="audio/wav"/>
 *     &lt;enumeration value="audio/mpeg"/>
 *     &lt;enumeration value="audio/mpg"/>
 *     &lt;enumeration value="audio/mp3"/>
 *     &lt;enumeration value="audio/x-mpeg"/>
 *     &lt;enumeration value="audio/midi"/>
 *     &lt;enumeration value="audio/x-realaudio"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "audio_mimetype")
@XmlEnum
public enum AudioMimetype {

    @XmlEnumValue("audio/wav")
    AUDIO_WAV("audio/wav"),
    @XmlEnumValue("audio/mpeg")
    AUDIO_MPEG("audio/mpeg"),
    @XmlEnumValue("audio/mpg")
    AUDIO_MPG("audio/mpg"),
    @XmlEnumValue("audio/mp3")
    AUDIO_MP_3("audio/mp3"),
    @XmlEnumValue("audio/x-mpeg")
    AUDIO_X_MPEG("audio/x-mpeg"),
    @XmlEnumValue("audio/midi")
    AUDIO_MIDI("audio/midi"),
    @XmlEnumValue("audio/x-realaudio")
    AUDIO_X_REALAUDIO("audio/x-realaudio");
    private final String value;

    AudioMimetype(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AudioMimetype fromValue(String v) {
        for (AudioMimetype c: AudioMimetype.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
