//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.20 at 09:54:46 PM CEST 
//


package it.sbn.iccu.metaag1;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for audio_spatialmetrics complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="audio_spatialmetrics">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="samplingfrequency" type="{http://www.iccu.sbn.it/metaAG1.pdf}samplingfrequencytype"/>
 *         &lt;choice>
 *           &lt;element name="bitpersample" type="{http://www.iccu.sbn.it/metaAG1.pdf}bitpersampletype"/>
 *           &lt;element name="bitrate" type="{http://www.iccu.sbn.it/metaAG1.pdf}bitratetype"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "audio_spatialmetrics", propOrder = {
    "samplingfrequency",
    "bitpersample",
    "bitrate"
})
public class AudioSpatialmetrics {

    protected float samplingfrequency;
    protected BigInteger bitpersample;
    protected BigInteger bitrate;

    /**
     * Gets the value of the samplingfrequency property.
     * 
     */
    public float getSamplingfrequency() {
        return samplingfrequency;
    }

    /**
     * Sets the value of the samplingfrequency property.
     * 
     */
    public void setSamplingfrequency(float value) {
        this.samplingfrequency = value;
    }

    /**
     * Gets the value of the bitpersample property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBitpersample() {
        return bitpersample;
    }

    /**
     * Sets the value of the bitpersample property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBitpersample(BigInteger value) {
        this.bitpersample = value;
    }

    /**
     * Gets the value of the bitrate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBitrate() {
        return bitrate;
    }

    /**
     * Sets the value of the bitrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBitrate(BigInteger value) {
        this.bitrate = value;
    }

}
