//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.20 at 09:54:46 PM CEST 
//


package it.sbn.iccu.metaag1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for audio_group complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="audio_group">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="audio_metrics" type="{http://www.iccu.sbn.it/metaAG1.pdf}audio_spatialmetrics"/>
 *         &lt;element name="format" type="{http://www.iccu.sbn.it/metaAG1.pdf}audio_format"/>
 *         &lt;element name="transcription" type="{http://www.iccu.sbn.it/metaAG1.pdf}audio_creation" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "audio_group", propOrder = {
    "audioMetrics",
    "format",
    "transcription"
})
public class AudioGroup {

    @XmlElement(name = "audio_metrics", required = true)
    protected AudioSpatialmetrics audioMetrics;
    @XmlElement(required = true)
    protected AudioFormat format;
    protected AudioCreation transcription;
    @XmlAttribute(name = "ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the audioMetrics property.
     * 
     * @return
     *     possible object is
     *     {@link AudioSpatialmetrics }
     *     
     */
    public AudioSpatialmetrics getAudioMetrics() {
        return audioMetrics;
    }

    /**
     * Sets the value of the audioMetrics property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioSpatialmetrics }
     *     
     */
    public void setAudioMetrics(AudioSpatialmetrics value) {
        this.audioMetrics = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link AudioFormat }
     *     
     */
    public AudioFormat getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioFormat }
     *     
     */
    public void setFormat(AudioFormat value) {
        this.format = value;
    }

    /**
     * Gets the value of the transcription property.
     * 
     * @return
     *     possible object is
     *     {@link AudioCreation }
     *     
     */
    public AudioCreation getTranscription() {
        return transcription;
    }

    /**
     * Sets the value of the transcription property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioCreation }
     *     
     */
    public void setTranscription(AudioCreation value) {
        this.transcription = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

}
