//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.20 at 09:54:46 PM CEST 
//


package it.sbn.iccu.metaag1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for audio_format complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="audio_format">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mime" type="{http://www.iccu.sbn.it/metaAG1.pdf}audio_mimetype"/>
 *         &lt;element name="compression" type="{http://www.iccu.sbn.it/metaAG1.pdf}compressiontype" minOccurs="0"/>
 *         &lt;element name="channel_configuration" type="{http://www.iccu.sbn.it/metaAG1.pdf}channelsconfigurationtype" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "audio_format", propOrder = {
    "name",
    "mime",
    "compression",
    "channelConfiguration"
})
public class AudioFormat {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected AudioMimetype mime;
    protected Compressiontype compression;
    @XmlElement(name = "channel_configuration")
    protected String channelConfiguration;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the mime property.
     * 
     * @return
     *     possible object is
     *     {@link AudioMimetype }
     *     
     */
    public AudioMimetype getMime() {
        return mime;
    }

    /**
     * Sets the value of the mime property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioMimetype }
     *     
     */
    public void setMime(AudioMimetype value) {
        this.mime = value;
    }

    /**
     * Gets the value of the compression property.
     * 
     * @return
     *     possible object is
     *     {@link Compressiontype }
     *     
     */
    public Compressiontype getCompression() {
        return compression;
    }

    /**
     * Sets the value of the compression property.
     * 
     * @param value
     *     allowed object is
     *     {@link Compressiontype }
     *     
     */
    public void setCompression(Compressiontype value) {
        this.compression = value;
    }

    /**
     * Gets the value of the channelConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChannelConfiguration() {
        return channelConfiguration;
    }

    /**
     * Sets the value of the channelConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannelConfiguration(String value) {
        this.channelConfiguration = value;
    }

}
