//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.20 at 09:54:46 PM CEST 
//


package it.sbn.iccu.metaag1;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for gen complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="gen">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stprog" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="collection" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="agency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="access_rights" type="{http://www.iccu.sbn.it/metaAG1.pdf}access_rights"/>
 *         &lt;element name="completeness" type="{http://www.iccu.sbn.it/metaAG1.pdf}completeness"/>
 *         &lt;element name="img_group" type="{http://www.iccu.sbn.it/metaAG1.pdf}img_group" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="audio_group" type="{http://www.iccu.sbn.it/metaAG1.pdf}audio_group" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="video_group" type="{http://www.iccu.sbn.it/metaAG1.pdf}video_group" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="creation" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="last_update" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "gen", propOrder = {
    "stprog",
    "collection",
    "agency",
    "accessRights",
    "completeness",
    "imgGroup",
    "audioGroup",
    "videoGroup"
})
public class Gen {

    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String stprog;
    @XmlSchemaType(name = "anyURI")
    protected String collection;
    @XmlElement(required = true)
    protected String agency;
    @XmlElement(name = "access_rights", required = true)
    protected BigInteger accessRights;
    @XmlElement(required = true)
    protected BigInteger completeness;
    @XmlElement(name = "img_group")
    protected List<ImgGroup> imgGroup;
    @XmlElement(name = "audio_group")
    protected List<AudioGroup> audioGroup;
    @XmlElement(name = "video_group")
    protected List<VideoGroup> videoGroup;
    @XmlAttribute(name = "creation")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creation;
    @XmlAttribute(name = "last_update")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastUpdate;

    /**
     * Gets the value of the stprog property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStprog() {
        return stprog;
    }

    /**
     * Sets the value of the stprog property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStprog(String value) {
        this.stprog = value;
    }

    /**
     * Gets the value of the collection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollection() {
        return collection;
    }

    /**
     * Sets the value of the collection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollection(String value) {
        this.collection = value;
    }

    /**
     * Gets the value of the agency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgency() {
        return agency;
    }

    /**
     * Sets the value of the agency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgency(String value) {
        this.agency = value;
    }

    /**
     * Gets the value of the accessRights property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAccessRights() {
        return accessRights;
    }

    /**
     * Sets the value of the accessRights property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAccessRights(BigInteger value) {
        this.accessRights = value;
    }

    /**
     * Gets the value of the completeness property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCompleteness() {
        return completeness;
    }

    /**
     * Sets the value of the completeness property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCompleteness(BigInteger value) {
        this.completeness = value;
    }

    /**
     * Gets the value of the imgGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the imgGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImgGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ImgGroup }
     * 
     * 
     */
    public List<ImgGroup> getImgGroup() {
        if (imgGroup == null) {
            imgGroup = new ArrayList<ImgGroup>();
        }
        return this.imgGroup;
    }

    /**
     * Gets the value of the audioGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the audioGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAudioGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AudioGroup }
     * 
     * 
     */
    public List<AudioGroup> getAudioGroup() {
        if (audioGroup == null) {
            audioGroup = new ArrayList<AudioGroup>();
        }
        return this.audioGroup;
    }

    /**
     * Gets the value of the videoGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the videoGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVideoGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VideoGroup }
     * 
     * 
     */
    public List<VideoGroup> getVideoGroup() {
        if (videoGroup == null) {
            videoGroup = new ArrayList<VideoGroup>();
        }
        return this.videoGroup;
    }

    /**
     * Gets the value of the creation property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreation() {
        return creation;
    }

    /**
     * Sets the value of the creation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreation(XMLGregorianCalendar value) {
        this.creation = value;
    }

    /**
     * Gets the value of the lastUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastUpdate() {
        return lastUpdate;
    }

    /**
     * Sets the value of the lastUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastUpdate(XMLGregorianCalendar value) {
        this.lastUpdate = value;
    }

}
