//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.20 at 09:54:46 PM CEST 
//


package it.sbn.iccu.metaag1;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.niso.pdfs.datadict.Dimensions;
import org.niso.pdfs.datadict.Format;
import org.niso.pdfs.datadict.ImageCreation;
import org.niso.pdfs.datadict.Spatialmetrics;
import org.niso.pdfs.datadict.Targetdata;


/**
 * <p>Java class for img complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="img">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sequence_number" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="nomenclature" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="usage" type="{http://www.iccu.sbn.it/metaAG1.pdf}usages" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="side" type="{http://www.iccu.sbn.it/metaAG1.pdf}side" minOccurs="0"/>
 *         &lt;element name="scale" type="{http://www.iccu.sbn.it/metaAG1.pdf}millimetric_scale" minOccurs="0"/>
 *         &lt;element name="file" type="{http://www.iccu.sbn.it/metaAG1.pdf}link"/>
 *         &lt;element name="md5" type="{http://www.niso.org/pdfs/DataDict.pdf}checksum"/>
 *         &lt;element name="filesize" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="image_dimensions" type="{http://www.niso.org/pdfs/DataDict.pdf}dimensions"/>
 *         &lt;element name="image_metrics" type="{http://www.niso.org/pdfs/DataDict.pdf}spatialmetrics" minOccurs="0"/>
 *         &lt;element name="ppi" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="dpi" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="format" type="{http://www.niso.org/pdfs/DataDict.pdf}format" minOccurs="0"/>
 *         &lt;element name="scanning" type="{http://www.niso.org/pdfs/DataDict.pdf}image_creation" minOccurs="0"/>
 *         &lt;element name="datetimecreated" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="target" type="{http://www.niso.org/pdfs/DataDict.pdf}targetdata" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="altimg" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="usage" type="{http://www.iccu.sbn.it/metaAG1.pdf}usages" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="file" type="{http://www.iccu.sbn.it/metaAG1.pdf}link"/>
 *                   &lt;element name="md5" type="{http://www.niso.org/pdfs/DataDict.pdf}checksum"/>
 *                   &lt;element name="filesize" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *                   &lt;element name="image_dimensions" type="{http://www.niso.org/pdfs/DataDict.pdf}dimensions"/>
 *                   &lt;element name="image_metrics" type="{http://www.niso.org/pdfs/DataDict.pdf}spatialmetrics" minOccurs="0"/>
 *                   &lt;element name="ppi" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *                   &lt;element name="dpi" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *                   &lt;element name="format" type="{http://www.niso.org/pdfs/DataDict.pdf}format" minOccurs="0"/>
 *                   &lt;element name="scanning" type="{http://www.niso.org/pdfs/DataDict.pdf}image_creation" minOccurs="0"/>
 *                   &lt;element name="datetimecreated" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="imggroupID" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="note" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="imggroupID" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="holdingsID" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "img", propOrder = {
    "sequenceNumber",
    "nomenclature",
    "usage",
    "side",
    "scale",
    "file",
    "md5",
    "filesize",
    "imageDimensions",
    "imageMetrics",
    "ppi",
    "dpi",
    "format",
    "scanning",
    "datetimecreated",
    "target",
    "altimg",
    "note"
})
public class Img {

    @XmlElement(name = "sequence_number", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger sequenceNumber;
    @XmlElement(required = true)
    protected String nomenclature;
    protected List<String> usage;
    protected Side side;
    protected BigInteger scale;
    @XmlElement(required = true)
    protected Link file;
    @XmlElement(required = true)
    protected String md5;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger filesize;
    @XmlElement(name = "image_dimensions", required = true)
    protected Dimensions imageDimensions;
    @XmlElement(name = "image_metrics")
    protected Spatialmetrics imageMetrics;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger ppi;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger dpi;
    protected Format format;
    protected ImageCreation scanning;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar datetimecreated;
    protected List<Targetdata> target;
    protected List<Img.Altimg> altimg;
    protected String note;
    @XmlAttribute(name = "imggroupID")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object imggroupID;
    @XmlAttribute(name = "holdingsID")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object holdingsID;

    /**
     * Gets the value of the sequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * Sets the value of the sequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSequenceNumber(BigInteger value) {
        this.sequenceNumber = value;
    }

    /**
     * Gets the value of the nomenclature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomenclature() {
        return nomenclature;
    }

    /**
     * Sets the value of the nomenclature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomenclature(String value) {
        this.nomenclature = value;
    }

    /**
     * Gets the value of the usage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the usage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUsage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getUsage() {
        if (usage == null) {
            usage = new ArrayList<String>();
        }
        return this.usage;
    }

    /**
     * Gets the value of the side property.
     * 
     * @return
     *     possible object is
     *     {@link Side }
     *     
     */
    public Side getSide() {
        return side;
    }

    /**
     * Sets the value of the side property.
     * 
     * @param value
     *     allowed object is
     *     {@link Side }
     *     
     */
    public void setSide(Side value) {
        this.side = value;
    }

    /**
     * Gets the value of the scale property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getScale() {
        return scale;
    }

    /**
     * Sets the value of the scale property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setScale(BigInteger value) {
        this.scale = value;
    }

    /**
     * Gets the value of the file property.
     * 
     * @return
     *     possible object is
     *     {@link Link }
     *     
     */
    public Link getFile() {
        return file;
    }

    /**
     * Sets the value of the file property.
     * 
     * @param value
     *     allowed object is
     *     {@link Link }
     *     
     */
    public void setFile(Link value) {
        this.file = value;
    }

    /**
     * Gets the value of the md5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMd5() {
        return md5;
    }

    /**
     * Sets the value of the md5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMd5(String value) {
        this.md5 = value;
    }

    /**
     * Gets the value of the filesize property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFilesize() {
        return filesize;
    }

    /**
     * Sets the value of the filesize property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFilesize(BigInteger value) {
        this.filesize = value;
    }

    /**
     * Gets the value of the imageDimensions property.
     * 
     * @return
     *     possible object is
     *     {@link Dimensions }
     *     
     */
    public Dimensions getImageDimensions() {
        return imageDimensions;
    }

    /**
     * Sets the value of the imageDimensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dimensions }
     *     
     */
    public void setImageDimensions(Dimensions value) {
        this.imageDimensions = value;
    }

    /**
     * Gets the value of the imageMetrics property.
     * 
     * @return
     *     possible object is
     *     {@link Spatialmetrics }
     *     
     */
    public Spatialmetrics getImageMetrics() {
        return imageMetrics;
    }

    /**
     * Sets the value of the imageMetrics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Spatialmetrics }
     *     
     */
    public void setImageMetrics(Spatialmetrics value) {
        this.imageMetrics = value;
    }

    /**
     * Gets the value of the ppi property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPpi() {
        return ppi;
    }

    /**
     * Sets the value of the ppi property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPpi(BigInteger value) {
        this.ppi = value;
    }

    /**
     * Gets the value of the dpi property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDpi() {
        return dpi;
    }

    /**
     * Sets the value of the dpi property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDpi(BigInteger value) {
        this.dpi = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link Format }
     *     
     */
    public Format getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link Format }
     *     
     */
    public void setFormat(Format value) {
        this.format = value;
    }

    /**
     * Gets the value of the scanning property.
     * 
     * @return
     *     possible object is
     *     {@link ImageCreation }
     *     
     */
    public ImageCreation getScanning() {
        return scanning;
    }

    /**
     * Sets the value of the scanning property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageCreation }
     *     
     */
    public void setScanning(ImageCreation value) {
        this.scanning = value;
    }

    /**
     * Gets the value of the datetimecreated property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatetimecreated() {
        return datetimecreated;
    }

    /**
     * Sets the value of the datetimecreated property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatetimecreated(XMLGregorianCalendar value) {
        this.datetimecreated = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the target property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTarget().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Targetdata }
     * 
     * 
     */
    public List<Targetdata> getTarget() {
        if (target == null) {
            target = new ArrayList<Targetdata>();
        }
        return this.target;
    }

    /**
     * Gets the value of the altimg property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the altimg property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAltimg().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Img.Altimg }
     * 
     * 
     */
    public List<Img.Altimg> getAltimg() {
        if (altimg == null) {
            altimg = new ArrayList<Img.Altimg>();
        }
        return this.altimg;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the imggroupID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getImggroupID() {
        return imggroupID;
    }

    /**
     * Sets the value of the imggroupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setImggroupID(Object value) {
        this.imggroupID = value;
    }

    /**
     * Gets the value of the holdingsID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getHoldingsID() {
        return holdingsID;
    }

    /**
     * Sets the value of the holdingsID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setHoldingsID(Object value) {
        this.holdingsID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="usage" type="{http://www.iccu.sbn.it/metaAG1.pdf}usages" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="file" type="{http://www.iccu.sbn.it/metaAG1.pdf}link"/>
     *         &lt;element name="md5" type="{http://www.niso.org/pdfs/DataDict.pdf}checksum"/>
     *         &lt;element name="filesize" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
     *         &lt;element name="image_dimensions" type="{http://www.niso.org/pdfs/DataDict.pdf}dimensions"/>
     *         &lt;element name="image_metrics" type="{http://www.niso.org/pdfs/DataDict.pdf}spatialmetrics" minOccurs="0"/>
     *         &lt;element name="ppi" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
     *         &lt;element name="dpi" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
     *         &lt;element name="format" type="{http://www.niso.org/pdfs/DataDict.pdf}format" minOccurs="0"/>
     *         &lt;element name="scanning" type="{http://www.niso.org/pdfs/DataDict.pdf}image_creation" minOccurs="0"/>
     *         &lt;element name="datetimecreated" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="imggroupID" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "usage",
        "file",
        "md5",
        "filesize",
        "imageDimensions",
        "imageMetrics",
        "ppi",
        "dpi",
        "format",
        "scanning",
        "datetimecreated"
    })
    public static class Altimg {

        protected List<String> usage;
        @XmlElement(required = true)
        protected Link file;
        @XmlElement(required = true)
        protected String md5;
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger filesize;
        @XmlElement(name = "image_dimensions", required = true)
        protected Dimensions imageDimensions;
        @XmlElement(name = "image_metrics")
        protected Spatialmetrics imageMetrics;
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger ppi;
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger dpi;
        protected Format format;
        protected ImageCreation scanning;
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar datetimecreated;
        @XmlAttribute(name = "imggroupID")
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        protected Object imggroupID;

        /**
         * Gets the value of the usage property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the usage property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUsage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getUsage() {
            if (usage == null) {
                usage = new ArrayList<String>();
            }
            return this.usage;
        }

        /**
         * Gets the value of the file property.
         * 
         * @return
         *     possible object is
         *     {@link Link }
         *     
         */
        public Link getFile() {
            return file;
        }

        /**
         * Sets the value of the file property.
         * 
         * @param value
         *     allowed object is
         *     {@link Link }
         *     
         */
        public void setFile(Link value) {
            this.file = value;
        }

        /**
         * Gets the value of the md5 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMd5() {
            return md5;
        }

        /**
         * Sets the value of the md5 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMd5(String value) {
            this.md5 = value;
        }

        /**
         * Gets the value of the filesize property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getFilesize() {
            return filesize;
        }

        /**
         * Sets the value of the filesize property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setFilesize(BigInteger value) {
            this.filesize = value;
        }

        /**
         * Gets the value of the imageDimensions property.
         * 
         * @return
         *     possible object is
         *     {@link Dimensions }
         *     
         */
        public Dimensions getImageDimensions() {
            return imageDimensions;
        }

        /**
         * Sets the value of the imageDimensions property.
         * 
         * @param value
         *     allowed object is
         *     {@link Dimensions }
         *     
         */
        public void setImageDimensions(Dimensions value) {
            this.imageDimensions = value;
        }

        /**
         * Gets the value of the imageMetrics property.
         * 
         * @return
         *     possible object is
         *     {@link Spatialmetrics }
         *     
         */
        public Spatialmetrics getImageMetrics() {
            return imageMetrics;
        }

        /**
         * Sets the value of the imageMetrics property.
         * 
         * @param value
         *     allowed object is
         *     {@link Spatialmetrics }
         *     
         */
        public void setImageMetrics(Spatialmetrics value) {
            this.imageMetrics = value;
        }

        /**
         * Gets the value of the ppi property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPpi() {
            return ppi;
        }

        /**
         * Sets the value of the ppi property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPpi(BigInteger value) {
            this.ppi = value;
        }

        /**
         * Gets the value of the dpi property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getDpi() {
            return dpi;
        }

        /**
         * Sets the value of the dpi property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setDpi(BigInteger value) {
            this.dpi = value;
        }

        /**
         * Gets the value of the format property.
         * 
         * @return
         *     possible object is
         *     {@link Format }
         *     
         */
        public Format getFormat() {
            return format;
        }

        /**
         * Sets the value of the format property.
         * 
         * @param value
         *     allowed object is
         *     {@link Format }
         *     
         */
        public void setFormat(Format value) {
            this.format = value;
        }

        /**
         * Gets the value of the scanning property.
         * 
         * @return
         *     possible object is
         *     {@link ImageCreation }
         *     
         */
        public ImageCreation getScanning() {
            return scanning;
        }

        /**
         * Sets the value of the scanning property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImageCreation }
         *     
         */
        public void setScanning(ImageCreation value) {
            this.scanning = value;
        }

        /**
         * Gets the value of the datetimecreated property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDatetimecreated() {
            return datetimecreated;
        }

        /**
         * Sets the value of the datetimecreated property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDatetimecreated(XMLGregorianCalendar value) {
            this.datetimecreated = value;
        }

        /**
         * Gets the value of the imggroupID property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getImggroupID() {
            return imggroupID;
        }

        /**
         * Sets the value of the imggroupID property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setImggroupID(Object value) {
            this.imggroupID = value;
        }

    }

}
