//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.20 at 09:54:46 PM CEST 
//


package it.sbn.iccu.metaag1;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.niso.pdfs.datadict.Format;
import org.niso.pdfs.datadict.ImageCreation;
import org.niso.pdfs.datadict.Spatialmetrics;


/**
 * <p>Java class for img_group complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="img_group">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="image_metrics" type="{http://www.niso.org/pdfs/DataDict.pdf}spatialmetrics"/>
 *         &lt;element name="ppi" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="dpi" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="format" type="{http://www.niso.org/pdfs/DataDict.pdf}format"/>
 *         &lt;element name="scanning" type="{http://www.niso.org/pdfs/DataDict.pdf}image_creation" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "img_group", propOrder = {
    "imageMetrics",
    "ppi",
    "dpi",
    "format",
    "scanning"
})
public class ImgGroup {

    @XmlElement(name = "image_metrics", required = true)
    protected Spatialmetrics imageMetrics;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger ppi;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger dpi;
    @XmlElement(required = true)
    protected Format format;
    protected ImageCreation scanning;
    @XmlAttribute(name = "ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the imageMetrics property.
     * 
     * @return
     *     possible object is
     *     {@link Spatialmetrics }
     *     
     */
    public Spatialmetrics getImageMetrics() {
        return imageMetrics;
    }

    /**
     * Sets the value of the imageMetrics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Spatialmetrics }
     *     
     */
    public void setImageMetrics(Spatialmetrics value) {
        this.imageMetrics = value;
    }

    /**
     * Gets the value of the ppi property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPpi() {
        return ppi;
    }

    /**
     * Sets the value of the ppi property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPpi(BigInteger value) {
        this.ppi = value;
    }

    /**
     * Gets the value of the dpi property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDpi() {
        return dpi;
    }

    /**
     * Sets the value of the dpi property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDpi(BigInteger value) {
        this.dpi = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link Format }
     *     
     */
    public Format getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link Format }
     *     
     */
    public void setFormat(Format value) {
        this.format = value;
    }

    /**
     * Gets the value of the scanning property.
     * 
     * @return
     *     possible object is
     *     {@link ImageCreation }
     *     
     */
    public ImageCreation getScanning() {
        return scanning;
    }

    /**
     * Sets the value of the scanning property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageCreation }
     *     
     */
    public void setScanning(ImageCreation value) {
        this.scanning = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

}
