//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.20 at 09:54:46 PM CEST 
//


package it.sbn.iccu.metaag1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for mimetype.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="mimetype">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="video/x-ms-asf"/>
 *     &lt;enumeration value="video/avi"/>
 *     &lt;enumeration value="video/mpeg"/>
 *     &lt;enumeration value="video/vnd.rn-realvideo"/>
 *     &lt;enumeration value="video/wmv"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "mimetype")
@XmlEnum
public enum Mimetype {

    @XmlEnumValue("video/x-ms-asf")
    VIDEO_X_MS_ASF("video/x-ms-asf"),
    @XmlEnumValue("video/avi")
    VIDEO_AVI("video/avi"),
    @XmlEnumValue("video/mpeg")
    VIDEO_MPEG("video/mpeg"),
    @XmlEnumValue("video/vnd.rn-realvideo")
    VIDEO_VND_RN_REALVIDEO("video/vnd.rn-realvideo"),
    @XmlEnumValue("video/wmv")
    VIDEO_WMV("video/wmv");
    private final String value;

    Mimetype(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Mimetype fromValue(String v) {
        for (Mimetype c: Mimetype.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
