//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.20 at 09:54:46 PM CEST 
//


package it.sbn.iccu.metaag1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for streamtypetype.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="streamtypetype">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Uncompressed"/>
 *     &lt;enumeration value="MPEG-1"/>
 *     &lt;enumeration value="MPEG-2"/>
 *     &lt;enumeration value="MPEG-4"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "streamtypetype")
@XmlEnum
public enum Streamtypetype {

    @XmlEnumValue("Uncompressed")
    UNCOMPRESSED("Uncompressed"),
    @XmlEnumValue("MPEG-1")
    MPEG_1("MPEG-1"),
    @XmlEnumValue("MPEG-2")
    MPEG_2("MPEG-2"),
    @XmlEnumValue("MPEG-4")
    MPEG_4("MPEG-4");
    private final String value;

    Streamtypetype(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Streamtypetype fromValue(String v) {
        for (Streamtypetype c: Streamtypetype.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
