//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.20 at 09:54:46 PM CEST 
//


package it.sbn.iccu.metaag1;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import org.purl.dc.elements._1.SimpleLiteral;


/**
 * <p>Java class for stru_element complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stru_element">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nomenclature" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *         &lt;element name="file" type="{http://www.iccu.sbn.it/metaAG1.pdf}link" minOccurs="0"/>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}identifier" minOccurs="0"/>
 *         &lt;element name="piece" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice minOccurs="0">
 *                   &lt;sequence>
 *                     &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="issue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="stpiece_per" type="{http://www.iccu.sbn.it/metaAG1.pdf}SICI"/>
 *                   &lt;/sequence>
 *                   &lt;sequence>
 *                     &lt;element name="part_number" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                     &lt;element name="part_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="stpiece_vol" type="{http://www.iccu.sbn.it/metaAG1.pdf}BICI"/>
 *                   &lt;/sequence>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="resource" type="{http://www.iccu.sbn.it/metaAG1.pdf}resource_type" minOccurs="0"/>
 *         &lt;element name="start" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="sequence_number" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                 &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}time" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="stop" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="sequence_number" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                 &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}time" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="descr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stru_element", propOrder = {
    "nomenclature",
    "file",
    "identifier",
    "piece",
    "resource",
    "start",
    "stop"
})
public class StruElement {

    protected Object nomenclature;
    protected Link file;
    @XmlElement(namespace = "http://purl.org/dc/elements/1.1/")
    protected SimpleLiteral identifier;
    protected StruElement.Piece piece;
    @XmlElement(defaultValue = "img")
    protected ResourceType resource;
    protected StruElement.Start start;
    protected StruElement.Stop stop;
    @XmlAttribute(name = "descr")
    protected String descr;
    @XmlAttribute(name = "num")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger num;

    /**
     * Gets the value of the nomenclature property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNomenclature() {
        return nomenclature;
    }

    /**
     * Sets the value of the nomenclature property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNomenclature(Object value) {
        this.nomenclature = value;
    }

    /**
     * Gets the value of the file property.
     * 
     * @return
     *     possible object is
     *     {@link Link }
     *     
     */
    public Link getFile() {
        return file;
    }

    /**
     * Sets the value of the file property.
     * 
     * @param value
     *     allowed object is
     *     {@link Link }
     *     
     */
    public void setFile(Link value) {
        this.file = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link SimpleLiteral }
     *     
     */
    public SimpleLiteral getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimpleLiteral }
     *     
     */
    public void setIdentifier(SimpleLiteral value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the piece property.
     * 
     * @return
     *     possible object is
     *     {@link StruElement.Piece }
     *     
     */
    public StruElement.Piece getPiece() {
        return piece;
    }

    /**
     * Sets the value of the piece property.
     * 
     * @param value
     *     allowed object is
     *     {@link StruElement.Piece }
     *     
     */
    public void setPiece(StruElement.Piece value) {
        this.piece = value;
    }

    /**
     * Gets the value of the resource property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceType }
     *     
     */
    public ResourceType getResource() {
        return resource;
    }

    /**
     * Sets the value of the resource property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceType }
     *     
     */
    public void setResource(ResourceType value) {
        this.resource = value;
    }

    /**
     * Gets the value of the start property.
     * 
     * @return
     *     possible object is
     *     {@link StruElement.Start }
     *     
     */
    public StruElement.Start getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     * @param value
     *     allowed object is
     *     {@link StruElement.Start }
     *     
     */
    public void setStart(StruElement.Start value) {
        this.start = value;
    }

    /**
     * Gets the value of the stop property.
     * 
     * @return
     *     possible object is
     *     {@link StruElement.Stop }
     *     
     */
    public StruElement.Stop getStop() {
        return stop;
    }

    /**
     * Sets the value of the stop property.
     * 
     * @param value
     *     allowed object is
     *     {@link StruElement.Stop }
     *     
     */
    public void setStop(StruElement.Stop value) {
        this.stop = value;
    }

    /**
     * Gets the value of the descr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescr() {
        return descr;
    }

    /**
     * Sets the value of the descr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescr(String value) {
        this.descr = value;
    }

    /**
     * Gets the value of the num property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNum() {
        return num;
    }

    /**
     * Sets the value of the num property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNum(BigInteger value) {
        this.num = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice minOccurs="0">
     *         &lt;sequence>
     *           &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *           &lt;element name="issue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *           &lt;element name="stpiece_per" type="{http://www.iccu.sbn.it/metaAG1.pdf}SICI"/>
     *         &lt;/sequence>
     *         &lt;sequence>
     *           &lt;element name="part_number" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *           &lt;element name="part_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *           &lt;element name="stpiece_vol" type="{http://www.iccu.sbn.it/metaAG1.pdf}BICI"/>
     *         &lt;/sequence>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "year",
        "issue",
        "stpiecePer",
        "partNumber",
        "partName",
        "stpieceVol"
    })
    public static class Piece {

        protected String year;
        protected String issue;
        @XmlElement(name = "stpiece_per")
        protected String stpiecePer;
        @XmlElement(name = "part_number")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger partNumber;
        @XmlElement(name = "part_name")
        protected String partName;
        @XmlElement(name = "stpiece_vol")
        protected String stpieceVol;

        /**
         * Gets the value of the year property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getYear() {
            return year;
        }

        /**
         * Sets the value of the year property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setYear(String value) {
            this.year = value;
        }

        /**
         * Gets the value of the issue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIssue() {
            return issue;
        }

        /**
         * Sets the value of the issue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIssue(String value) {
            this.issue = value;
        }

        /**
         * Gets the value of the stpiecePer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStpiecePer() {
            return stpiecePer;
        }

        /**
         * Sets the value of the stpiecePer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStpiecePer(String value) {
            this.stpiecePer = value;
        }

        /**
         * Gets the value of the partNumber property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPartNumber() {
            return partNumber;
        }

        /**
         * Sets the value of the partNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPartNumber(BigInteger value) {
            this.partNumber = value;
        }

        /**
         * Gets the value of the partName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPartName() {
            return partName;
        }

        /**
         * Sets the value of the partName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPartName(String value) {
            this.partName = value;
        }

        /**
         * Gets the value of the stpieceVol property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStpieceVol() {
            return stpieceVol;
        }

        /**
         * Sets the value of the stpieceVol property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStpieceVol(String value) {
            this.stpieceVol = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="sequence_number" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *       &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}time" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Start {

        @XmlAttribute(name = "sequence_number", required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger sequenceNumber;
        @XmlAttribute(name = "offset")
        @XmlSchemaType(name = "time")
        protected XMLGregorianCalendar offset;

        /**
         * Gets the value of the sequenceNumber property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getSequenceNumber() {
            return sequenceNumber;
        }

        /**
         * Sets the value of the sequenceNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setSequenceNumber(BigInteger value) {
            this.sequenceNumber = value;
        }

        /**
         * Gets the value of the offset property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getOffset() {
            return offset;
        }

        /**
         * Sets the value of the offset property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setOffset(XMLGregorianCalendar value) {
            this.offset = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="sequence_number" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
     *       &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}time" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Stop {

        @XmlAttribute(name = "sequence_number", required = true)
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger sequenceNumber;
        @XmlAttribute(name = "offset")
        @XmlSchemaType(name = "time")
        protected XMLGregorianCalendar offset;

        /**
         * Gets the value of the sequenceNumber property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getSequenceNumber() {
            return sequenceNumber;
        }

        /**
         * Sets the value of the sequenceNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setSequenceNumber(BigInteger value) {
            this.sequenceNumber = value;
        }

        /**
         * Gets the value of the offset property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getOffset() {
            return offset;
        }

        /**
         * Sets the value of the offset property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setOffset(XMLGregorianCalendar value) {
            this.offset = value;
        }

    }

}
