//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.20 at 09:54:46 PM CEST 
//


package it.sbn.iccu.metaag1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for video_format complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="video_format">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mime" type="{http://www.iccu.sbn.it/metaAG1.pdf}mimetype"/>
 *         &lt;element name="videoformat" type="{http://www.iccu.sbn.it/metaAG1.pdf}videoformattype"/>
 *         &lt;element name="encode" type="{http://www.iccu.sbn.it/metaAG1.pdf}encodetype" minOccurs="0"/>
 *         &lt;element name="streamtype" type="{http://www.iccu.sbn.it/metaAG1.pdf}streamtypetype" minOccurs="0"/>
 *         &lt;element name="codec" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "video_format", propOrder = {
    "name",
    "mime",
    "videoformat",
    "encode",
    "streamtype",
    "codec"
})
public class VideoFormat {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected Mimetype mime;
    @XmlElement(required = true)
    protected Videoformattype videoformat;
    protected Encodetype encode;
    protected Streamtypetype streamtype;
    protected String codec;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the mime property.
     * 
     * @return
     *     possible object is
     *     {@link Mimetype }
     *     
     */
    public Mimetype getMime() {
        return mime;
    }

    /**
     * Sets the value of the mime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Mimetype }
     *     
     */
    public void setMime(Mimetype value) {
        this.mime = value;
    }

    /**
     * Gets the value of the videoformat property.
     * 
     * @return
     *     possible object is
     *     {@link Videoformattype }
     *     
     */
    public Videoformattype getVideoformat() {
        return videoformat;
    }

    /**
     * Sets the value of the videoformat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Videoformattype }
     *     
     */
    public void setVideoformat(Videoformattype value) {
        this.videoformat = value;
    }

    /**
     * Gets the value of the encode property.
     * 
     * @return
     *     possible object is
     *     {@link Encodetype }
     *     
     */
    public Encodetype getEncode() {
        return encode;
    }

    /**
     * Sets the value of the encode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Encodetype }
     *     
     */
    public void setEncode(Encodetype value) {
        this.encode = value;
    }

    /**
     * Gets the value of the streamtype property.
     * 
     * @return
     *     possible object is
     *     {@link Streamtypetype }
     *     
     */
    public Streamtypetype getStreamtype() {
        return streamtype;
    }

    /**
     * Sets the value of the streamtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Streamtypetype }
     *     
     */
    public void setStreamtype(Streamtypetype value) {
        this.streamtype = value;
    }

    /**
     * Gets the value of the codec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodec() {
        return codec;
    }

    /**
     * Sets the value of the codec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodec(String value) {
        this.codec = value;
    }

}
