//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.20 at 09:54:46 PM CEST 
//


package it.sbn.iccu.metaag1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for video_group complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="video_group">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="video_metrics" type="{http://www.iccu.sbn.it/metaAG1.pdf}video_spatialmetrics"/>
 *         &lt;element name="format" type="{http://www.iccu.sbn.it/metaAG1.pdf}video_format"/>
 *         &lt;element name="digitisation" type="{http://www.iccu.sbn.it/metaAG1.pdf}video_creation" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "video_group", propOrder = {
    "videoMetrics",
    "format",
    "digitisation"
})
public class VideoGroup {

    @XmlElement(name = "video_metrics", required = true)
    protected VideoSpatialmetrics videoMetrics;
    @XmlElement(required = true)
    protected VideoFormat format;
    protected VideoCreation digitisation;
    @XmlAttribute(name = "ID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the videoMetrics property.
     * 
     * @return
     *     possible object is
     *     {@link VideoSpatialmetrics }
     *     
     */
    public VideoSpatialmetrics getVideoMetrics() {
        return videoMetrics;
    }

    /**
     * Sets the value of the videoMetrics property.
     * 
     * @param value
     *     allowed object is
     *     {@link VideoSpatialmetrics }
     *     
     */
    public void setVideoMetrics(VideoSpatialmetrics value) {
        this.videoMetrics = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link VideoFormat }
     *     
     */
    public VideoFormat getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link VideoFormat }
     *     
     */
    public void setFormat(VideoFormat value) {
        this.format = value;
    }

    /**
     * Gets the value of the digitisation property.
     * 
     * @return
     *     possible object is
     *     {@link VideoCreation }
     *     
     */
    public VideoCreation getDigitisation() {
        return digitisation;
    }

    /**
     * Sets the value of the digitisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link VideoCreation }
     *     
     */
    public void setDigitisation(VideoCreation value) {
        this.digitisation = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

}
