//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.23 at 05:10:44 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://purl.org/dc/elements/1.1/")
package org.purl.dc.elements._1;
